version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - DB_HOST=mysql
      - DB_USER=mick
      - DB_PASSWORD=root
      - DB_NAME=commerce
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend
    ports:
      - "5002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    ports:
      - "5001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'commerce'
      MYSQL_USER: 'mick'
      MYSQL_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
